# ================================================================================================ #
# Description: Runs the analysis comparing the treated & control / before & after populations
# to produce output for submission to checking as part of the outcomes-framework social housing test case 
# (paper 5). The analysis mainly consists of cross tabs for the sample means and sd for comparing the 
# Before-After populations. There are 3 components to the analysis - 
#   1. Main analysis that compares the group that was housed 12 months before GSS interview to the group housed 
#       15 months after.
#   2. Validation of main analysis comparing the group that was housed 12 months before GSS interview to the 
#       group housed 12 months after
#   3. Validation of main analysis comparing the group that was housed 12 months before GSS interview to the 
#       group housed 15 months after, but after applying a weighting to this group using propensity scores.
#
# Input: 
#
# Output: Comma separated text files suitable for opening in Excel, containing all the prepared output
# and ready for confidentialization. Also, plots of all the cross-tables (with an option to save these)
# for ease of visualization.
# 
# Author: S. Anastasiadis
#
# Dependencies:
# SIAtoolbox - for reading SQL database
# data_loading_and_preparation.R - for data preparation
# function_for_treat_control.R - for data analysis
#
# Notes: Run-time is approx 4 minutes
#
# History (reverse order): 
# 28 Nov 2017 SA v1
# 13 Sep 2018 BV Reorganised code, added comments
# ================================================================================================ #

library(SIAtoolbox)
library(RODBC)
library(ggplot2)
library(Matching)
library(dplyr)
library(reshape2)
library(weights)
library(robustbase)
library(xlsx)
library(stringr)

# set working directory
setwd("~/Network-Shares/Datalab-MA/MAA2016-15 Supporting the Social Investment Unit/outcomes_framework/workstream5/rprogs")

# start time
print("Start time:")
print(Sys.time())

################ Parameters ################
# number of nearest neighbours to consider for matching process (1-4 recommended, 2 considered best)
NUM_RECORDS_TO_MATCH <- 2
# Number of repetitions needed for doing bootstrap sampling that's used in the generation of confidence intervals
NUM_REPS <- 400
# Decide whether the plots generated by the analysis is to be saved for later reference
SAVE_PLOTS <- TRUE

# DB name
databasename <- "IDI_Clean_20171020"
sandpitname <-"[DL-MAA2016-15]"

################ Source ################

# functions
source('./function_for_treat_control.R')
# data preparation
source('./data_loading_and_preparation.R')


################ analysis when dependent variable = treat_control_main ################
# runs the analysis against the explanotory variables:

# for the treatment/control "main" groups = new applications and gss_itw to housed between -12 and 15 months
dependent_var <- "treat_control_main"

# crosstabs (+ CI by bootstrap) + plots + t-test betweeen the 2 groups
analysis_wrapper(dataset, dependent_var, SAVE_PLOTS, columns_to_analyse)

# robust regressions
reg_formulas <- cbind(
          # formulas for the regressions
          c("life_satisfaction_bin ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
          ,"life_satisfaction_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
          ,"gss_pq_house_mold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
          ,"gss_pq_house_cold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
          ,"house_crowding_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
          ,"safety_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
          ),
          # regression family (binomial / gaussian)
          c("binomial", "gaussian", "binomial", "binomial", "binomial", "binomial")
          )

robust_glm_wrapper(reg_formulas, dataset, dependent_var)


################ analysis when dependent variable = treat_control_sen ################
# runs the analysis against the explanotory variables:

# for the treatment/control "sensitivity" groups = new applications and gss_itw to housed between -12 and 12 months
dependent_var <- "treat_control_sen"

# crosstabs (+ CI by bootstrap) + plots + t-test betweeen the 2 groups
analysis_wrapper(dataset, dependent_var, SAVE_PLOTS, columns_to_analyse)


# robust regressions
reg_formulas <- cbind(
  # formulas for the regressions
  c("life_satisfaction_bin ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
    ,"life_satisfaction_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
    ,"gss_pq_house_mold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
    ,"gss_pq_house_cold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
    ,"house_crowding_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
    ,"safety_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
  ),
  # regression family (binomial / gaussian)
  c("binomial", "gaussian", "binomial", "binomial", "binomial", "binomial")
)

robust_glm_wrapper(reg_formulas, dataset, dependent_var)


######################################################
# propensity matching for building a weighted treatment group

################ matching undertaking ################

# column for matching variable
dependent_var <- "treat_control_match"
# temporary dataset
dataset_match <- filter(dataset, treat_control_main != "IGNORE")
dataset_match[[dependent_var]] <- dataset_match[["treat_control_main"]]
# purge NAs
contains_NAs <- apply(dataset_match[,c('sex'
                                     ,'eth_european'
                                     ,'eth_maori'
                                     ,'eth_pacifica'
                                     ,'eth_other'
                                     ,'as_at_age'
                                     ,'highest_qual')], 1, function(x) any(is.na(x)))
dataset_match <- filter(dataset_match, !contains_NAs)

# prep data for matching
treatment.control.ind  <- ifelse(dataset_match[[dependent_var]] == 'CONTROL',1,0)
# basic
matrix.values.to.match.on  <- dataset_match[,c('sex'
                                         ,'eth_european'
                                         ,'eth_maori'
                                         ,'eth_pacifica'
                                         ,'eth_other'
                                         ,'as_at_age'
                                         ,'highest_qual')]
# convert columns to factors
for(name in names(matrix.values.to.match.on)){
  if(class(matrix.values.to.match.on[[name]]) == "character"){
    matrix.values.to.match.on[[name]] <- as.factor(matrix.values.to.match.on[[name]])
  }
}

# matching
rr  <- Match(Tr=treatment.control.ind,X=data.matrix(matrix.values.to.match.on),M=NUM_RECORDS_TO_MATCH)

# add weights into dataset
dataset_match$wgt <- 0
dataset_match[rr$index.treated,'wgt'] <- 1
for(ii in 1:length(rr$index.control)){
  idx <- rr$index.control[ii]
  dataset_match[idx,'wgt'] <- dataset_match[idx,'wgt'] + rr$weights[ii]
}
# ignore cases where weights are zero
dataset_match[dataset_match$wgt == 0,dependent_var] <- "IGNORE"

# view summary of weighted relationships
print('count of weights by treated & control')
print(table(dataset_match[[dependent_var]],dataset_match$wgt))

################ analysis when dependent variable = treat_control_match ################

dependent_var <- "treat_control_match"

# crosstabs (+ CI by bootstrap) + plots + t-test betweeen the 2 groups
analysis_wrapper(dataset_match, dependent_var, SAVE_PLOTS, columns_to_analyse)

# weighted regressions glm
reg_formulas <- cbind(
  # formulas for the regressions
  c("life_satisfaction_bin ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
    ,"life_satisfaction_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
    ,"gss_pq_house_mold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
    ,"gss_pq_house_cold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
    ,"house_crowding_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
    ,"safety_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_income_numeric+1) + treat_control_main + wave"
  ),
  # regression family (binomial / gaussian)
  c("quasibinomial", "gaussian", "quasibinomial", "quasibinomial", "quasibinomial", "quasibinomial")
)

glm_wrapper(reg_formulas, dataset_match, dependent_var)

